### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by worldspawn** [hendryluk/cormo#3]
https://github.com/hendryluk/cormo/blob/master/src/Cormo/Interceptions/InterceptorAttribute.cs#L9

``` csharp
public interface IAroundnvokeInterceptor
```

**Comment by hendryluk** [comment]
Ha it is, cheers. Btw interceptor feature is currently still not implemented. The public api is there (with the typo), but it wont do anything yet at the moment

**Comment by hendryluk** [comment]
Fixed
