### ISSUE TITLE
Would u consider implementing CommonServiceLocator?  

### ISSUE THREAD

**Issue by worldspawn** [hendryluk/cormo#4]
So this could wired up with something like mediatr?

**Comment by hendryluk** [comment]
Yep i cant see why not. I'd do that, especially if its only to be used for mediatr. But people shouldnt be using service locator directly though because it messes up with contexts and injection point (or the lack of them)

**Comment by hendryluk** [comment]
Btw i may not be familiar with the full feature of mediatr but i think it could be redundant since cdi already has component-discover and resolution, decorator, and event handling built-in. What else can we gain from mediatr?

**Comment by hendryluk** [comment]
Btw by "messed up with context" what i meant is that when u request things manually from common-service-locator api (i.e *not* within mediatr), cormo won't be able to keep track of it, i.e unmanaged. It also cant tell who's asking. So certain things may not behave the same way (eg lifecycles). Should be fine in most cases but should only be used in dire circumstances

**Comment by hendryluk** [comment]
@worldspawn This has now been implemented: https://github.com/hendryluk/cormo/blob/master/src/Cormo.CommonServiceLocator/CormoServiceLocator.cs

Up on nuget: http://www.nuget.org/packages/Cormo.CommonServiceLocator/. Would that work straightaway with Mediatr? Ideally so or else we can make the module wire that up automatically
